import { describe, it, expect } from "vitest";
import { buildHtml } from "../src/server/services/html-export";

describe("html-export", () => {
  it("produces self-contained HTML with inline CSS", () => {
    const buffer = buildHtml({
      packName: "Test Pack",
      projectName: "Test Project",
      versionNumber: 1,
      sourceNames: ["Source 1"],
      generationDate: "1 January 2026",
      data: {
        summary: null,
        nonGoals: null,
        openQuestions: [],
        assumptions: [],
        decisions: [],
        risks: [],
        stories: [],
      },
    });
    const str = buffer.toString("utf-8");
    expect(str).toContain("<!DOCTYPE html>");
    expect(str).toContain("<style>");
    expect(str).toContain("#1B2A4A");
    expect(str).toContain("#0D8B8B");
  });

  it("includes table of contents", () => {
    const buffer = buildHtml({
      packName: "P",
      projectName: "P",
      versionNumber: 1,
      sourceNames: [],
      generationDate: "1 Jan 2026",
      data: {
        summary: "A summary",
        nonGoals: null,
        openQuestions: [],
        assumptions: ["A1"],
        decisions: [],
        risks: [],
        stories: [{ id: "s1", persona: "User", want: "X", soThat: "Y", acceptanceCriteria: [] }],
      },
    });
    const str = buffer.toString("utf-8");
    expect(str).toContain("Table of Contents");
    expect(str).toContain("href=\"#summary\"");
    expect(str).toContain("href=\"#stories\"");
    expect(str).toContain("href=\"#assumptions\"");
  });

  it("includes all artefact sections", () => {
    const buffer = buildHtml({
      packName: "P",
      projectName: "P",
      versionNumber: 1,
      sourceNames: [],
      generationDate: "1 Jan 2026",
      data: {
        summary: "Summary text",
        nonGoals: "Non-goals text",
        openQuestions: ["Q1"],
        assumptions: ["A1"],
        decisions: ["D1"],
        risks: ["R1"],
        stories: [
          {
            id: "s1",
            persona: "As a user",
            want: "I want X",
            soThat: "So that Y",
            acceptanceCriteria: [{ given: "G", when: "W", then: "T" }],
            evidenceCount: 1,
          },
        ],
      },
    });
    const str = buffer.toString("utf-8");
    expect(str).toContain("Summary text");
    expect(str).toContain("Non-goals text");
    expect(str).toContain("Q1");
    expect(str).toContain("A1");
    expect(str).toContain("D1");
    expect(str).toContain("R1");
    expect(str).toContain("As a user");
    expect(str).toContain("Given G When W Then T");
    expect(str).toContain("badge-green");
  });

  it("includes QA summary and footer", () => {
    const buffer = buildHtml({
      packName: "P",
      projectName: "P",
      versionNumber: 1,
      sourceNames: [],
      generationDate: "1 Jan 2026",
      data: {
        summary: null,
        nonGoals: null,
        openQuestions: [],
        assumptions: [],
        decisions: [],
        risks: [],
        stories: [],
      },
      qaStats: { pass: 5, warn: 2, fail: 1 },
    });
    const str = buffer.toString("utf-8");
    expect(str).toContain("QA Summary");
    expect(str).toContain("Pass: 5");
    expect(str).toContain("Warn: 2");
    expect(str).toContain("Fail: 1");
    expect(str).toContain("Generated by Reqvolt");
  });
});
